name: CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release
    - name: Pack
      if: github.event_name != 'pull_request'
      run: dotnet pack -c Release -o ./artifacts/NuGet
    - name: Artifacts
      if: github.event_name != 'pull_request' && matrix.os == 'windows-2019'
      uses: actions/upload-artifact@master
      with:
        name: NuGet
        path: ./artifacts/NuGet

  publish-windows:
    name: Publish windows-latest
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Publish
      if: github.event_name != 'pull_request'
      run: |
        dotnet publish -c Release /p:PublishTrimmed=True /p:PublishReadyToRun=True -f netcoreapp3.1 -r win7-x64 -o ./artifacts/TypefaceUtil-netcoreapp3.1-win7-x64 ./src/TypefaceUtil/TypefaceUtil.csproj
        dotnet publish -c Release /p:PublishTrimmed=False /p:PublishReadyToRun=False -f netcoreapp3.1 -r win-x64 -o ./artifacts/TypefaceUtil-win-x64 ./src/TypefaceUtil/TypefaceUtil.csproj
        del artifacts\TypefaceUtil-win-x64\*.pdb
        del artifacts\TypefaceUtil-win-x64\*.json
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: TypefaceUtil-netcoreapp3.1-win7-x64
        path: ./artifacts/TypefaceUtil-netcoreapp3.1-win7-x64
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: TypefaceUtil-win-x64
        path: ./artifacts/TypefaceUtil-win-x64

  publish-ubuntu:
    name: Publish ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Publish
      if: github.event_name != 'pull_request'
      run: |
        dotnet publish -c Release /p:PublishTrimmed=True /p:PublishReadyToRun=True -f netcoreapp3.1 -r debian.8-x64 -o ./artifacts/TypefaceUtil-netcoreapp3.1-debian.8-x64 ./src/TypefaceUtil/TypefaceUtil.csproj
        dotnet publish -c Release /p:PublishTrimmed=True /p:PublishReadyToRun=True -f netcoreapp3.1 -r ubuntu.14.04-x64 -o ./artifacts/TypefaceUtil-netcoreapp3.1-ubuntu.14.04-x64 ./src/TypefaceUtil/TypefaceUtil.csproj
        sudo apt-get install clang zlib1g-dev libkrb5-dev libtinfo5
        dotnet publish -c Release /p:PublishTrimmed=False /p:PublishReadyToRun=False -f netcoreapp3.1 -r linux-x64 -o ./artifacts/TypefaceUtil-linux-x64 ./src/TypefaceUtil/TypefaceUtil.csproj
        strip ./artifacts/TypefaceUtil-linux-x64/TypefaceUtil
        rm ./artifacts/TypefaceUtil-linux-x64/*.pdb
        rm ./artifacts/TypefaceUtil-linux-x64/*.json
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: TypefaceUtil-netcoreapp3.1-debian.8-x64
        path: ./artifacts/TypefaceUtil-netcoreapp3.1-debian.8-x64
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: TypefaceUtil-netcoreapp3.1-ubuntu.14.04-x64
        path: ./artifacts/TypefaceUtil-netcoreapp3.1-ubuntu.14.04-x64
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: TypefaceUtil-linux-x64
        path: ./artifacts/TypefaceUtil-linux-x64

  publish-macOS:
    name: Publish macOS-latest
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Publish
      if: github.event_name != 'pull_request'
      run: |
        dotnet publish -c Release /p:PublishTrimmed=True /p:PublishReadyToRun=True -f netcoreapp3.1 -r osx.10.12-x64 -o ./artifacts/TypefaceUtil-netcoreapp3.1-osx.10.12-x64 ./src/TypefaceUtil/TypefaceUtil.csproj
        dotnet publish -c Release /p:PublishTrimmed=False /p:PublishReadyToRun=False -f netcoreapp3.1 -r osx-x64 -o ./artifacts/TypefaceUtil-osx-x64 ./src/TypefaceUtil/TypefaceUtil.csproj
        strip ./artifacts/TypefaceUtil-osx-x64/TypefaceUtil
        rm ./artifacts/TypefaceUtil-osx-x64/*.pdb
        rm ./artifacts/TypefaceUtil-osx-x64/*.json
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: TypefaceUtil-netcoreapp3.1-osx.10.12-x64
        path: ./artifacts/TypefaceUtil-netcoreapp3.1-osx.10.12-x64
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: TypefaceUtil-netcoreapp3.1-osx.10.12-x64
        path: ./artifacts/TypefaceUtil-netcoreapp3.1-osx.10.12-x64
